### ISSUE TITLE
New branch not creating directory

### ISSUE THREAD

**Issue by ryanlong1004** [esmf-org/esmf-branch-summary#15]
![image](https://user-images.githubusercontent.com/69773028/156049779-b976e936-9e9b-40e2-9a4e-0622819b10dc.png)

The branch "jedwards_pio_update2" should be going to a new branch.  It's instead going to "jedwards_pio_update".

https://github.com/esmf-org/esmf-test-summary/blob/main/jedwards_pio_update/v8.3.0b08-90-g763a128.md

**Comment by ryanlong1004** [comment]
@rsdunlapiv running without the ```-b``` flag will pickup all new branches.

**Comment by rsdunlapiv** [comment]
Cori has jedwards/pio_update2 artifacts:
https://github.com/esmf-org/esmf-test-artifacts/tree/cori/jedwards_pio_update2/cori/intel/19.0.3

but these do not appear in the summary table:
https://github.com/esmf-org/esmf-test-summary/blob/main/jedwards_pio_update2/v8.3.0b08-90-g763a128.md

**Comment by ryanlong1004** [comment]
Resolved.

@rsdunlapiv The link you sent has since been updated and I see the  jedwards_pio_update2 branches in it.

Closing the issue.
