### ISSUE TITLE
Include NetCDF version in summary table

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-branch-summary#16]
In the summary table, add a column for the NetCDF version.  This information can be determined from the build.log file.  See example log file [here](https://raw.githubusercontent.com/esmf-org/esmf-test-artifacts/discover/develop/discover/intel/2020/g/intelmpi/19.1.3.304/out/build.log) that includes the NetCDF version.

Example output from the build log:

```
--------------------------------------------------------------
NetCDF library version: netCDF 4.8.0-development
NetCDF Fortran version: netCDF-Fortran 4.5.4-development
```

Here, the 4.8.0 (C) and 4.5.4 (Fortran) should be parsed out and put into a new column in the summary table.  Review other build.log files to see if the format is consistent for other versions of NetCDF.

**Comment by rsdunlapiv** [comment]
@ryanlong1004 we would like to have this one in soon to facilitate the release process

**Comment by ryanlong1004** [comment]
@rsdunlapiv I have a working version here:

https://github.com/ryanlong1004/esmf-test-summary/tree/main/develop

Some of the build.log don't contain those lines.  I'm looking for an alternative.

Ryan
