### ISSUE TITLE
Move build_passed column and rename

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-branch-summary#3]
Currently the "build_passed" is the first column of the summary table.The default sorting seems to give highest priority to it, and consequently all the "0" lines come first, followed by the "1" lines. Sorting by "host" makes a lot more sense to me instead. Also, I personally expect to first see the columns with configuration information, before the columns with results, "build_passed" as the first results column.

I propose to move the "build_passed" column to sit between the "os" and "unit_pass" columns.

Further I propose renaming "build_passed" to "lib-build", and translate "0"->"fail, "1"->"pass".

**Comment by ryanlong1004** [comment]
Fixed in v1.1.0
